# Generated by Django 4.0.5 on 2022-07-07 07:43

import accoutUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accoutUser', '0004_alter_userprofilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to=accoutUser.models.get_user_img_name, verbose_name='Фото пользователя'),
        ),
    ]
