# Generated by Django 4.0.5 on 2022-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBord', '0004_ebordmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='categories/', verbose_name='Изображение товара'),
        ),
    ]
