# Generated by Django 4.0.5 on 2022-07-04 11:00

from django.db import migrations, models
import eBord.models


class Migration(migrations.Migration):

    dependencies = [
        ('eBord', '0005_categorymodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['name'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=eBord.models.get_categories_filename, verbose_name='Изображение товара'),
        ),
    ]
