# Generated by Django 4.0.5 on 2022-07-04 11:17

from django.db import migrations, models
import eBord.models


class Migration(migrations.Migration):

    dependencies = [
        ('eBord', '0006_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default='ads/default.jpeg', upload_to=eBord.models.get_categories_filename, verbose_name='Изображение товара'),
        ),
    ]
